micronaut:
  application:
    name: covid19Aggregator
    instance: ${random.uuid}
    version: 0.1

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**


endpoints:
  health:
    enabled: true
    endpoints:
      login:
        enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    url:
      enabled: true

  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true